### ISSUE TITLE
Failed pre-update status code check (HTTP code 418).

### ISSUE THREAD

**Issue by danielbair** [danielbachhuber/update-verify#31]
When trying to update plugins or themes I am now getting this...
Fetching pre-update site response...
-> HTTP status code: 418
-> I'm a little teapot.
Warning: Failed pre-update status code check (HTTP code 418).

wp cli core us up-to-date on my server when I checked.

I have checked the error logs on my server, and I don't see any HTTP code 418 being thrown.

I also posted this issue on the wp-cli/wp-cli repo...
https://github.com/wp-cli/wp-cli/issues/5532

**Comment by danielbachhuber** [comment]
Hi @danielbair,

Per your [other comment](https://github.com/wp-cli/wp-cli/issues/5532#issuecomment-843751594), the most likely issue is that better-wp-security is blocking the request. You'll need to allow your server's IP address to make requests to the site.

**Comment by danielbair** [comment]
I have removed the update-verify package and wp-cli is working now. 

Better wp security doesn't issue a 418 http response from my searching of their code.

DreamHost does use mod_security and is known to issue http 418 but there are no 418 in the error logs.

I cannot find where this is coming from.

**Comment by danielbair** [comment]
Ok, I setup a test wp install and was able to discover that this problem only exists when the better-wp-security plugin is installed. I have filed a bug report with them for now and my local wp-cli workaround with update-verity disabled is what I am
able to use for now.
